<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE results [
<!ATTLIST result id CDATA #REQUIRED>
<!ELEMENT result (code,message)>
<!ELEMENT code (#PCDATA)>
<!ELEMENT message (#PCDATA)>]>
<results>
    
	<!--登录 -->
	<result id="101">
		<code>101</code>
		<message>登录成功</message>
	</result>
	<result id="102">
		<code>102</code>
		<message>密码错误</message>
	</result>
	<result id="103">
		<code>103</code>
		<message>用户名不存在</message>
	</result>
	<result id="500">
		<code>500</code>
		<message>服务器异常</message>
	</result>

	<!--注册 -->
	<result id="201">
		<code>201</code>
		<message>注册成功</message>
	</result>
	<result id="202">
		<code>202</code>
		<message>用户已存在</message>
	</result>

	<!-- 上传图片 -->
	<result id="300">
	    <code>300</code>
	    <message>上传成功</message>
	</result>
		<result id="301">
	    <code>301</code>
	    <message>上传失败</message>
	</result>
</results>
